const programECO = {
  stage_1: {
    april_17: [
      {      
        type: 'Seminario',
        type_en:'Seminar',        
        title: 'Mitigación de las emisiones de metano mediante la gestión de residuos orgánicos: Estrategias, economía y técnicas ',
        title_en: 'Mitigating methane emissions by managing organic waste: Strategies, Economics, Tecniques',
        location: 'ECO Stage',
        duration: '3 hrs.',
        hour: '11:00 - 14:00 hrs.',        
        resume: 'Se centrarán en diversos enfoques para evitar que los residuos orgánicos generen y emitan biogás de vertedero. Las técnicas abordadas son: compostaje, digestión anaerobia y recogida de gas de vertedero. El seminario también estudiará el aspecto financiero en relación con la necesidad de instituciones internacionales disponibles para apoyar la inversión en estas nuevas tecnologías sostenibles.',
        resume_en: 'The event will focus on various approaches to prevent organic waste to generate and emit biogas from landfills. The techniques addressed are: composting, anaerobic digestion and landfill gas collection. The seminar will also address the financial aspect regarding the need for international institutions available to support the investment into these new, sustainable technologies.',   
        speakers : 'Jorge Israel García Ochoa | Izarelli Rosillo | Marco Ricci | Paula García | R3VER. Linares',
        position : "Secretario de SEMADET, Gobierno del Estado de Jalisco | Universidad de Querétaro | Comité Científico y Técnico de Ecomondo | Clean Air Task Force",
        position_en : "Secretary of SEMADET, Jalisco State Government | University of Querétaro | Ecomondo STC | Clean Air Task Force",
        // speakers: [
        //   {
        //     id: 1,
        //   },
        //   {
        //     id: 2,
        //   },
        //   {
        //     id: 3,
        //   },
        //   {
        //     id: 4,
        //   },
        //   {
        //     id: 5,
        //   }
        // ],
      },
      {        
        type: 'Seminario',
        type_en:'Seminar',
        title: 'Historias de éxito en modelos circulares de negocio',
        title_en: 'Success stories in circular business models',
        location: 'ECO Stage',
        duration: '2 hrs.',
        hour: '15:00 - 17:00 hrs.',
        resume: 'Las industrias pueden utilizar soluciones de economía circular para mejorar la sustentabilidad y la productividad. El taller presentará casos de estudio e innovaciones de plantas productivas en México de los sectores: Bioenergía, Alimentos y Bebidas, Automotriz y más.',
        resume_en: 'Industries may use circular economy solutions to improve sustainability and productivity. The workshop will present case studies and innovations of productive plants in Mexico of the sectors: Bio Energy, Food and Beverage, Automotive and more.',
        speakers : 'Cecile De Mauleon',
        position : "Directora de Camexital, Cámara de Comercio Mexicana en Italia",
        position_en : "Director of Camexital, Mexican Chamber of Commerce in Italy",
      }      
    ],
    april_18: [
      {
        type: 'Seminario',
        type_en:'Seminar',
        title: 'Presentación de la Guía del Profesional, de ISWA Asociación Internacional de Residuos Sólidos',
        title_en: 'ISWA International Solid Waste Association - Practitioners Guide',
        location: 'ECO Stage',
        duration: '2 hrs.',
        hour: '11:00 a 13:00 hrs.',
        resume: 'En el evento se presentará la Guía del Profesional centrada en la cuestión de los contaminantes en el reciclado de residuos orgánicos, un tema que aborda también otros flujos de reciclado como envases, RAEE, etc. El documento será presentado por uno de los autores principales y los ponentes se encuentran entre los colaboradores de la Guía o expertos de América Latina y de México. Organizado/ promovido en cooperación con la Red Regional ISWA para América Latina coordinada por ARS-Argentina.',
        resume_en: 'The event will present the Practitioner’s Guide focusing on the issue of contaminant in organic waste recycling, a topic which addresses also other recycling streams such as packaging, WEEE, etc. The document will be presented by one of the lead-authors and the speakers are among the contributors of the Guide or experts from Latin-American and from Mexico.  Organised/promoted in cooperation with the ISWA Regional Network for Latin America coordinated by ARS-Argentina.',
        speakers : 'Francisco Galván | Marco Ricci | Gustavo Solórzano',
        position : "DSLatinoamericana, Presidente) | ISWA WG BTW | DSLatinoamericana-México",
        position_en : "Chairman of DSLatinoamericana | ISWA WG BTW | Head of International Relations of DS Latinoamericana-Mexico",
      },
      {
        type: 'Seminario',
        type_en:'Seminar',
        title: 'Ciudades verdes y desarrollo sostenible en América Latina: nuevas fronteras de la Economía Circular',
        title_en: 'Green cities and sustainable development in Latin America: new frontiers of the circular economy',
        location: 'ECO Stage',
        duration: '1.5 hrs.',
        hour: '15:30 a 17:00 hrs.',
        resume: 'Ciudades verdes y desarrollo sostenible en América Latina: nuevas fronteras de la Economía Circular',
        resume_en: 'Green cities and sustainable development in Latin America: new frontiers of the circular economy',
        speakers : 'Giselle Canahuati',
        position : "Secretario Socioeconómico - IILA Organización Internacional Italo-Latinoamericana",
        position_en : "Socioeconomic Secretary of IILA International Italo-Latin American Organization",
      },
    ],
    april_19: [
      {
        type: 'Seminario',
        type_en:'Seminar',
        title: 'Gestión de residuos de vehículos al final de su vida útil',
        title_en: 'Waste management from end-of-life vehicles (EoL) vehicles',
        location: 'ECO Stage',
        duration: '1 hrs.',
        hour: '11:00 a 12:00 hrs.',
        resume: 'Con la llegada de la movilidad eléctrica y la presión para la descarbonización del sistema de transporte, se están generando cuellos de botella para diferentes residuos, ante la premura de sustituir los vehículos, generando componentes útiles (autopartes)',
        resume_en: 'With the arrival of electric mobility and the pressure for the decarbonization of the transportation system, bottlenecks are being generated for different wastes, since there is pressure to replace vehicles faster, generating useful components (auto parts)',
        speakers : '' ,
        position : "",
        position_en : "",
      },
      {
        type: 'Seminario',
        type_en:'Seminar',
        title: 'Residuos eléctricos y electrónicos (RAEE) en América Latina',
        title_en: 'Waste management from end-of-life vehicles (EoL) vehicles',
        location: 'ECO Stage',
        duration: '1 hrs.',
        hour: '12:15 a 13:15 hrs.',
        resume: 'Se discutirán las legislaciones y procedimientos para el manejo de estos residuos, casos de éxito en Centroamérica, la necesidad de promover en México la recolección y clasificación adecuada, así como el aprovechamiento de la oportunidad comercial.',
        resume_en: 'Legislation and procedures for the management of this waste, success stories in Central America, the need to promote in Mexico the collection and proper classification, exploitation of the commercial opportunity.',
        speakers : '',
        position : "",
        position_en : "",
      },
    ],   
  },
  stage_2: {
    april_17: [
      {        
        type: 'Seminario',
        type_en:'Seminar',
        title: 'Curso de formación: Adopción de innovaciones hídricas en el estado de Jalisco',
        title_en: 'Training course: Water innovations uptake in the state of Jalisco',
        location: 'Piso 1',
        duration: '3 hrs.',
        hour: '11:00 a 14:00 hrs.',
        resume:'Las innovaciones cercanas al mercado integradas en la infraestructura hídrica existente o nueva son el desafío al que la transferencia de conocimientos y tecnología debe hacer frente. El taller presentará innovaciones relevantes que han alcanzado un alto nivel de preparación tecnológica (TRL), incluyendo criterios de diseño y estrategias para integrarlos en estudios de casos reales.',
        resume_en:'Close to market innovations integrated in the existing or new water infrastructure. This is the challenge that knowledge and technology transfer should address. The workshop will present relevant innovations that have reached high technology readiness level (TRL) including design criteria and strategies to integrate them in real case studies',
        speakers : 'Mario Guadalupe González Pérez',
        position : "Miembro del Sistema Nacional de Investigadores del Consejo Nacional de Tecnología de México",
        position_en : "Member of the National System of Researchers of the National Council of Technology of Mexico",      
      },
      {
        type: 'Seminario',
        type_en:'Seminar',
        title: 'Tratamiento sostenible y reutilización segura de aguas residuales industriales',
        title_en: 'Industrial wastewater sustainable treatment and safe reuse',
        location: 'ECO Stage',
        duration: '1.5 hrs.',
        hour: '17:00 - 18:30 hrs.',
        resume: 'Esta mesa redonda de comparación Italia/ Europa/ México pondrá a discusión estudios de tratamiento sostenible de aguas industriales así como aguas residuales, y la reutilización de este recurso, con casos de Europa y diferentes estados de México.',
        resume_en: 'International round table comparing: Italy/Europe, Mexico on the topic of sustainable industrial water and wastewater treatment and water reuse. Case studies from Europe and different Mexico states.',
        speakers : 'Francesco Fatone | Jesús Manríquez | José Tello',
        position : "Miembro de la Asociación Internacional del Agua IWA | Gerente de tratamiento y reutilización de SAPAL León, Guanajuato México | Conservación Ambiental CIBNOR ",
        position_en : "International Water Association IWA fellow | Treatment and reuse manager at SAPAL | Environmental Conservation CIBNOR",
      }
    ],
    april_18: [
      {
        type: 'Seminario',
        type_en:'Seminar',
        title: 'Políticas, planes, regulaciones y mejores prácticas a nivel de cuenca para la protección integrada de la calidad y uso del agua superficial y subterránea',
        title_en: 'Catchment-wide policies, plans, regulations and best practice for integrated safeguarding surface and groundwater quality and use',
        location: 'ECO Stage',
        duration: '1.5 hrs.',
        hour: '13:00 a 14:30 hrs.',
        resume: 'El uso excesivo o la contaminación de la calidad de las aguas superficiales o subterráneas puede afectar a amplias zonas y requerir mucho tiempo y grandes inversiones para su reparación. Se necesitan políticas y normativas que abarquen toda la cuenca para impulsar planes de acción integrados. En el taller se presentarán estudios de casos mexicanos y se entablará un debate constructivo con expertos europeos.',
        resume_en: 'Overuse or pollution of surface or groundwater quality might impact wide areas and require long time and high investments for remediation. Catchment-wide policies and regulations are needed to drive integrated action plans. The workshop will present Mexican case studied and discussion with European experts will drive the constructive discussion.',
        speakers : 'Cindy McCulligh | Francesco Fatone',
        position : "",
        position_en : "", 
      }
    ],
    april_19: [
      {
        type: 'Información por confirmar',
        type_en:'Information to be completed',
        title: 'PRÓXIMAMENTE',
        title_en: 'COMING SOON',
        location: '',
        duration: '0 hrs.',
        hour: '00:00 a 00:00 hrs.',
        resume: '',
        resume_en: '',
        speakers : '',
        position : "",
        position_en : "",
      }
    ],
  }, 
}

export { programECO }
