const speakers=[
    {
        id:9,
        name: 'José Tello',
        avatar: '/ecomondo/speakers/jose_tello.webp',
        resume_es: 'Director de Aguas en la consultora •••Centro de Estudios e Investigación en Asuntos Públicos (Ceiap S.C.). Es consultor para organizaciones como NatGeo, GIZ, WWF y la CCA, así como de la Embajada de los Países Bajos en México. Participó como moderador del evento oficial de México sobre ríos e inclusión social, en la Conferencia de la ONU sobre el Agua 2023.Cuenta con estudios de maestría en Holanda y en Australia; además de un Doctorado en Uso y Conservación de Recursos Naturales, por el Centro de Investigaciones Biológicas del Noroeste (CIBNOR) en México.',
        resume_en: 'Water Director at consulting firm CEIAP SC (•••Centro de Estudios e Investigación en Asuntos Públicos SC). Consultant for organizations such as NatGeo, GIZ, WWF and the CEC, and the Netherlands Embassy in Mexico. Participate as Moderator of Mexico’s official event on rivers and social inclusion, at the 2023 UN Water Conference.Master studies in The Netherlands and Australia. PhD in Use and Conservation of Natural Resources from the Biological Research Centre of the North-West (CIBNOR) in Mexico.',
    },
    {
        id:14,
        name: 'Mario Guadalupe González Pérez',
        avatar: '/ecomondo/speakers/mario_guadalupe.webp',
        resume_es: 'Ingeniero civil y académico mexicano, especializado en temas hídricos. Cuenta con licenciatura en Ingeniería Civil por la Universidad Autónoma de Sinaloa, maestría en Administración de la Construcción por la Universidad Nacional Autónoma de México y doctorado en Ciudad, Territorio y Sustentabilidad por la Universidad de Guadalajara. Ha sido director de Ingeniería en el Centro Universitario UTEG y profesor en diversas universidades públicas y privadas. Posee amplia experiencia docente impartiendo materias de ingeniería civil, hidráulica, matemáticas, estadística, entre otras. Es autor y coautor de múltiples publicaciones científicas y ha recibido financiamiento del Consejo Nacional de Ciencia y Tecnología y la Secretaría de Educación Pública para investigación. Actualmente pertenece al Sistema Nacional de Investigadores y se desempeña en el Departamento de Estudios del Agua y Energía del Centro Universitario de Ciencias Exactas e Ingenierías de la Universidad de Guadalajara.',
        resume_en: 'Civil engineer and academic, specialized in water resources. He holds a Bachelor\'s degree in Civil Engineering from the Autonomous University of Sinaloa, a Master\'s degree in Construction Management from the National Autonomous University of Mexico, and a PhD in City, Territory and Sustainability from the University of Guadalajara. He has served as Director of Engineering at the University Center UTEG and as professor at various public and private universities. He has extensive teaching experience in subjects such as civil engineering, hydraulics, mathematics, statistics, among others. He is the author and co-author of multiple scientific publications and has received funding from the National Council of Science and Technology and the Ministry of Public Education for research projects. He is currently a member of the National System of Researchers and works in the Department of Water and Energy Studies at the University Center of Exact Sciences and Engineering of the University of Guadalajara.',
    },
    {
        id:1,
        name: 'Jorge Israel García Ochoa', 
        avatar: '/ecomondo/speakers/user_img.webp',
        resume_es: 'La información se está actualizando. Por favor, mantente atento.',
        resume_en: 'Information is being updated. Please stay tuned.',
    },
    {
        id:2,
        name: 'Izarelly Rosillo', 
        avatar: '/ecomondo/speakers/user_img.webp',
        resume_es: 'La información se está actualizando. Por favor, mantente atento.',
        resume_en: 'Information is being updated. Please stay tuned.',
    },
    {
        id:3,
        name: 'Marco Ricci', 
        avatar: '/ecomondo/speakers/user_img.webp',
        resume_es: 'Físico y Doctor en Gestión Ambiental, experto en estrategias, planificación, recolección y compostaje de residuos orgánicos. Experto Senior de CIC – Asociación Italiana de Compostaje y Biogás, investiga y coopera para numerosas organizaciones internacionales. Miembro del STC de ISWA International.',
        resume_en: 'Physicist and Ph.D. in Environmental Management, expert in organic waste strategies, planning, collection and composting.Senior Expert of CIC – Italian Composting and Biogas Association, researches and cooperates for numerous international organisations. Member of the STC of ISWA international.',
    },
    {
        id:4,
        name: 'Paula García', 
        avatar: '/ecomondo/speakers/user_img.webp',
        resume_es: 'La información se está actualizando. Por favor, mantente atento.',
        resume_en: 'Information is being updated. Please stay tuned.',
    },
    {
        id:5,
        name: 'R3VER. Linares - México', 
        avatar: '/ecomondo/speakers/user_img.webp',
        resume_es: 'La información se está actualizando. Por favor, mantente atento.',
        resume_en: 'Information is being updated. Please stay tuned.',
    },  
    {
        id:6,
        name: 'Cecile De Mauleon',
        avatar: '/ecomondo/speakers/user_img.webp',
        resume: '(Directora de Camexital, Cámara de Comercio Mexicana en Italia) MÁS PONENTES POR CONFIRMAR',
    },
    {
        id:7,
        name: 'Francesco Fatone',
        avatar: '/ecomondo/speakers/user_img.webp',
        resume_es: 'La información se está actualizando. Por favor, mantente atento.',
        resume_en: 'Information is being updated. Please stay tuned.',
    },
    {
        id:8,
        name: 'Jesús Manríquez',
        avatar: '/ecomondo/speakers/user_img.webp',
        resume_es: 'La información se está actualizando. Por favor, mantente atento.',
        resume_en: 'Information is being updated. Please stay tuned.',
    },
    {
        id:10,
        name: 'Francisco Galvan',
        avatar: '/ecomondo/speakers/user_img.webp',
        resume_es: 'La información se está actualizando. Por favor, mantente atento.',
        resume_en: 'Information is being updated. Please stay tuned.',
    },
    {
        id:11,
        name: 'Gustavo Solorzano',
        avatar: '/ecomondo/speakers/user_img.webp',
        resume_es: 'La información se está actualizando. Por favor, mantente atento.',
        resume_en: 'Information is being updated. Please stay tuned.',
    },
    {
        id:12,
        name: 'Cindy McCulligh',
        avatar: '/ecomondo/speakers/user_img.webp',
        resume_es: 'La información se está actualizando. Por favor, mantente atento.',
        resume_en: 'Information is being updated. Please stay tuned.',
    },
    {
        id:13,
        name: 'Giselle Canahuati',
        avatar: '/ecomondo/speakers/user_img.webp',
        resume_es: 'La información se está actualizando. Por favor, mantente atento.',
        resume_en: 'Information is being updated. Please stay tuned.',
    }
]
export { speakers }
  