const speakers=[
    {
        id:9,
        name: 'José Tello',
        avatar: '/ecomondo/speakers/jose_tello.webp',
        resume_es: 'Director de Aguas en la consultora •••Centro de Estudios e Investigación en Asuntos Públicos (Ceiap S.C.). Es consultor para organizaciones como NatGeo, GIZ, WWF y la CCA, así como de la Embajada de los Países Bajos en México. Participó como moderador del evento oficial de México sobre ríos e inclusión social, en la Conferencia de la ONU sobre el Agua 2023.Cuenta con estudios de maestría en Holanda y en Australia; además de un Doctorado en Uso y Conservación de Recursos Naturales, por el Centro de Investigaciones Biológicas del Noroeste (CIBNOR) en México.',
        resume_en: 'Water Director at consulting firm CEIAP SC (•••Centro de Estudios e Investigación en Asuntos Públicos SC). Consultant for organizations such as NatGeo, GIZ, WWF and the CEC, and the Netherlands Embassy in Mexico. Participate as Moderator of Mexico’s official event on rivers and social inclusion, at the 2023 UN Water Conference. Master studies in The Netherlands and Australia. PhD in Use and Conservation of Natural Resources from the Biological Research Centre of the North-West (CIBNOR) in Mexico.'

    },
    {
        id:14,
        name: 'Mario Guadalupe González Pérez',
        avatar: '/ecomondo/speakers/mario_guadalupe.webp',
        resume_es: 'Ingeniero civil y académico mexicano, especializado en temas hídricos. Cuenta con licenciatura en Ingeniería Civil por la Universidad Autónoma de Sinaloa, maestría en Administración de la Construcción por la Universidad Nacional Autónoma de México y doctorado en Ciudad, Territorio y Sustentabilidad por la Universidad de Guadalajara. Ha sido director de Ingeniería en el Centro Universitario UTEG y profesor en diversas universidades públicas y privadas. Posee amplia experiencia docente impartiendo materias de ingeniería civil, hidráulica, matemáticas, estadística, entre otras. Es autor y coautor de múltiples publicaciones científicas y ha recibido financiamiento del Consejo Nacional de Ciencia y Tecnología y la Secretaría de Educación Pública para investigación. Actualmente pertenece al Sistema Nacional de Investigadores y se desempeña en el Departamento de Estudios del Agua y Energía del Centro Universitario de Ciencias Exactas e Ingenierías de la Universidad de Guadalajara.',
        resume_en: 'Mexican civil engineer and academic, specialized in water issues. He holds a degree in Civil Engineering from the Universidad Autónoma de Sinaloa; a masters degree in Construction Management from the Universidad Nacional Autónoma de México; and a doctorate in City, Territory and Sustainability from the Universidad de Guadalajara. He has been director of Engineering at the UTEG University Center and professor at several public and private universities. He has extensive teaching experience in civil engineering, hydraulics, mathematics, statistics, among others. He is author and co-author of several scientific publications and has received research funding from the National Council of Science and Technology and the Ministry of Public Education. Currently, he belongs to the National System of Researchers and works in the Department of Water and Energy Studies of the University Center of Exact Sciences and Engineering of the University of Guadalajara.'},
    {
        id:1,
        name: 'Jorge Israel García Ochoa', 
        avatar: '/ecomondo/speakers/israel-garcia-ochoa.webp',
        resume_es: 'La información se está actualizando. Por favor, mantente atento.',
        resume_en: 'Information is being updated. Please stay tuned.',
    },
    {
        id:2,
        name: 'Izarelly Rosillo', 
        avatar: '/ecomondo/speakers/izarelly-rosillo.webp',
        resume_es: 'Tiene una destacada carrera como abogada litigante e investigadora en derechos humanos y medio ambiente; además, es Doctora en Derecho por la Universidad Autónoma de Querétaro. Su influencia se ha extendido a nivel nacional e internacional, contribuyendo a la elaboración de legislaciones tanto locales como internacionales, así como a la formulación de planes y programas ambientales. Ha colaborado como consultora para diversas instituciones y organizaciones, como el Banco Mundial, el Banco Interamericano de Desarrollo, la ONU Medio Ambiente y varias agencias de cooperación, en proyectos relacionados con la gestión integral de residuos sólidos y la promoción de una economía circular. Su expertise también se ha aplicado en la elaboración de leyes estatales y nacionales, así como en la capacitación y asesoramiento en derecho ambiental. Como conferencista, ha participado en congresos nacionales e internacionales, representando a México en discusiones sobre temas como el derecho al agua y saneamiento. Además, ha obtenido reconocimientos por su labor, incluyendo el nombramiento honorífico como integrante del Comité Mundial sobre Desarrollo Sostenible y la Presea Ignacio Ruiz Calado. Actualmente, es miembro del Sistema Nacional de Investigadores del Consejo Nacional de Ciencia y Tecnología en México y coordina el proyecto "Reduciendo los riesgos ambientales y globales a través del monitoreo y desarrollo de sustento alternativo para el sector minero de mercurio primario en México". Además, es autora de varios libros y artículos, abordando temas relacionados con políticas públicas ambientales, gestión de residuos y ética jurídica.',
        resume_en: 'She has a distinguished career as a litigation lawyer and researcher in human rights and the environment; she is also a Doctor of Law from the Autonomous University of Querétaro. Her influence has extended nationally and internationally, contributing to the development of both local and international legislation, as well as the formulation of environmental plans and programs. She has collaborated as a consultant for various institutions and organizations, such as the World Bank, the Inter-American Development Bank, UN Environment, and various cooperation agencies, in projects related to integrated solid waste management and the promotion of a circular economy. Her expertise has also been applied in the drafting of state and national laws, as well as in training and advising on environmental law. As a speaker, she has participated in national and international congresses, representing Mexico in discussions on topics such as the right to water and sanitation. In addition, she has received recognition for her work, including the honorary appointment as a member of the World Committee on Sustainable Development and the Ignacio Ruiz Calado Award. Currently, she is a member of the National System of Researchers of the National Council of Science and Technology in Mexico and coordinates the project "Reducing Environmental and Global Risks through Monitoring and Developing Alternative Livelihoods for the Primary Mercury Mining Sector in Mexico." She is also the author of several books and articles, addressing topics related to environmental public policies, waste management, and legal ethics.'
    },
    {
        id:3,
        name: 'Marco Ricci', 
        avatar: '/ecomondo/speakers/MARCO_RICCI.webp',
        resume_es: 'Físico y Doctor en Gestión Ambiental, experto en estrategias, planificación, recolección y compostaje de residuos orgánicos. Experto Senior de CIC – Asociación Italiana de Compostaje y Biogás, donde investiga y coopera para numerosas organizaciones internacionales. Miembro del STC de ISWA International.',
        resume_en: 'Physicist and Ph.D. in Environmental Management, expert in organic waste strategies, planning, collection and composting.Senior Expert of CIC – Italian Composting and Biogas Association, researches and cooperates for numerous international organisations. Member of the STC of ISWA international.',
    },
    {
        id:4,
        name: 'Paula García', 
        avatar: '/ecomondo/speakers/Paula_Garcia_HOLLEY.webp',
        resume_es: 'Se incorporó a CATF en 2022 como Gerente de Políticas Públicas  para América Latina. En este cargo, apoya al equipo de Prevención de la Contaminación por Metano en sus esfuerzos por reducir las emisiones de metano de los  sectores de residuos sólidos e hidrocarburos abogando por regulaciones y políticas ambiciosas y técnicamente sólidas. Antes de unirse a CATF, trabajó en ICF, enfocándose en sustancias que agotan la capa de ozono; y en el análisis de hidrofluorocarbonos para la División de Protección Estratosférica de la Agencia de Protección Ambiental de EE. UU., así mismo trabajó en apoyo al cumplimiento ambiental para la Agencia de EE. UU. para el Desarrollo Internacional. Además, laboró en la Agencia de Seguridad, Energía y Medio Ambiente de México (ASEA), en el desarrollo e implementación de regulaciones de metano para el sector de petróleo y gas. Tiene un B.Sc. en Química por la Universidad Nacional Autónoma de México (UNAM) y M.Sc. en Química de la Universidad Northwestern.',
        resume_en: 'he joined CATF in 2022 as Public Policy Manager for Latin America. In this role, she supports the Methane Pollution Prevention team in its efforts to reduce methane emissions from the solid waste and hydrocarbon sectors by advocating for ambitious and technically sound regulations and policies. Before joining CATF, she worked at ICF, focusing on ozone-depleting substances; and analyzing hydrofluorocarbons for the U.S. Environmental Protection Agencys Stratospheric Protection Division. She also worked in support of environmental compliance for the U.S. Agency for International Development. Additionally, she worked at the Mexican Agency for Safety, Energy and Environment (ASEA), in the development and implementation of methane regulations for the oil and gas sector. She holds a B.Sc. in Chemistry from the National Autonomous University of Mexico (UNAM) and an M.Sc. in Chemistry from Northwestern University'
    },
    {
        id:5,
        name: 'Rosendo Tamez', 
        avatar: '/ecomondo/speakers/rosendo-tamez_v2.webp',
        resume_es: 'Ingeniero Industrial, con maestría en Dirección. Además, se dedica al diseño de Modelos de Gestión de Residuos Sólidos Urbanos. Actualmente, es Encargado de Nuevo negocios y proyectos de Digestión para la Reducción de Metano y Aprovechamiento de la Fracción Orgánica, para empresa R3VER y Grupo Eggersmann en LATAM.',
        resume_en: 'Industrial Engineer, with a Master\'s Degree in Management. In addition, he is dedicated to the design of Urban Solid Waste Management Models. Currently, he is in charge of new business and Digestion projects for Methane Reduction and Organic Fraction Utilization for R3VER and Eggersmann Group in LATAM.',
    },  
    {
        id:6,
        name: 'Cecile De Mauleon',
        avatar: '/ecomondo/speakers/CECILE_DE_MAULEON.webp',
        resume: '(Directora de Camexital, Cámara de Comercio Mexicana en Italia) MÁS PONENTES POR CONFIRMAR',
        resume_es: 'La información se está actualizando. Por favor, mantente atento.',
        resume_en: 'Information is being updated. Please stay tuned.',
    },
    {
        id:7,
        name: 'Francesco Fatone',
        avatar: '/ecomondo/speakers/francesco-fatone.webp',
        resume_es: 'Profesor Titular de Ingeniería Química y Ambiental en la Universidad Politécnica de Marche, Italia, destaca por su liderazgo y contribuciones en múltiples ámbitos. Desde 2013, ha asegurado más de 10 millones de euros en financiamiento de proyectos de la UE y más de 2 millones de fondos privados. Ha liderado numerosas iniciativas de investigación, como el proyecto "SMART-Plant" de Horizon2020, y ha sido parte de más de 15 proyectos internacionales de I+D. Además, desempeña roles destacados en revistas científicas, conferencias internacionales y comités de expertos, abordando temas cruciales como la economía circular y la gestión del agua. Su extenso trabajo se refleja en más de 140 artículos indexados en SCOPUS, citados más de 4600 veces, y en su reconocimiento global, incluyendo un doctorado honoris causa y consultorías internacionales',
        resume_en: 'Full Professor of Chemical and Environmental Engineering at the Polytechnic University of Marche, Italy, he is noted for his leadership and contributions in multiple fields. Since 2013, he has secured more than €10 million in EU project funding and more than €2 million in private funding. He has led numerous research initiatives, such as the Horizon2020 "SMART-Plant" project, and has been part of more than 15 international R&D projects. In addition, he plays leading roles in scientific journals, international conferences and expert committees, addressing crucial topics such as circular economy and water management. His extensive work is reflected in more than 140 articles indexed in SCOPUS, cited more than 4600 times, and in his global recognition, including an honorary doctorate and international consultancies.',
    },
    {
        id:8,
        name: 'Jesús Manríquez',
        avatar: '/ecomondo/speakers/JESUSMANRIQUEZ.webp',
        resume_es: 'La información se está actualizando. Por favor, mantente atento.',
        resume_en: 'Information is being updated. Please stay tuned.',
    },
    {
        id:10,
        name: 'Francisco Galván',
        avatar: '/ecomondo/speakers/FRANCISCO_GALVAN.webp',
        resume_es: 'La información se está actualizando. Por favor, mantente atento.',
        resume_en: 'Information is being updated. Please stay tuned.',
    },
    {
        id:11,
        name: 'Gustavo Solórzano ',
        avatar: '/ecomondo/speakers/GUSTAVO_SOLORZANO.webp',
        resume_es: 'Ingeniero industrial, Maestría en Ingeniería Ambiental de la UNAM y Universidad de París. Consultor internacional en residuos para Banco Mundial, BID, GIZ, PNUMA, entre otros. Director de Asuntos Internacionales, DS LATAM (Miembro Nacional ISWA – México).  Representante de AIDIS ante la Coalición para el Cierre de Basurales en América Latina y el Caribe del PNUMA. Co-autor de What a Waste 2.0 con Banco Mundial',
        resume_en: 'Industrial Engineer, Master\'s Degree in Environmental Engineering from UNAM and University of Paris. International consultant on waste for the World Bank, IDB, GIZ, UNEP, among others. Director of International Affairs, DS LATAM (ISWA National Member - Mexico).  AIDIS representative to UNEP\'s Coalition for Landfill Closure in Latin America and the Caribbean. Co-author of What a Waste 2.0 with the World Bank.',
    },
    {
        id:12,
        name: 'Cindy McCulligh',
        avatar: '/ecomondo/speakers/cindy-mcculigh.webp',
        resume_es: 'Profesora-investigadora del Centro de Investigaciones y Estudios Superiores en Antropología Social (CIESAS), Unidad Occidente. Estudió la maestría en Estudios Ambientales, en York University (Toronto, Canadá); y el doctorado en Ciencias Sociales, con Especialidad en Antropología Social, en CIESAS Occidente. Su tesis recibió el premio doctoral 2018 de la red internacional Waterlat-Gobacit. Ha publicado diversos artículos y libros sobre las temáticas de gestión del agua, conflictos socioambientales, agroextractivismo, regulación ambiental en particular de la industria, y las afectaciones sociales y ambientales de los procesos de contaminación ambiental. Aborda estos temas desde los enfoques de la ecología política y la justicia ambiental. En 2023, publicó su libro "Sewer of Progress: Corporations, Institutionalized Corruption, and the Struggle for the Santiago River", con MIT Press.',
        resume_en: 'Professor-researcher at the Centro de Investigaciones y Estudios Superiores en Antropología Social (CIESAS), Unidad Occidente. She studied a Master\'s degree in Environmental Studies at York University (Toronto, Canada); and a PhD in Social Sciences, with a specialization in Social Anthropology, at CIESAS Occidente. Her thesis received the 2018 doctoral award from the international network Waterlat-Gobacit. He has published several articles and books on the topics of water management, socio-environmental conflicts, agro-extractivism, environmental regulation in particular of industry, and the social and environmental affectations of environmental pollution processes. He approaches these issues from the approaches of political ecology and environmental justice. In 2023, he published his book "Sewer of Progress: Corporations, Institutionalized Corruption, and the Struggle for the Santiago River", with MIT Press.',
    },
    {
        id:13,
        name: 'Giselle Canahuati',
        avatar: '/ecomondo/speakers/GISELLE_CANAHUATI.webp',
        resume_es: 'La información se está actualizando. Por favor, mantente atento.',
        resume_en: 'Information is being updated. Please stay tuned.',
    },
    {
        id:15,
        name: 'Luisa González',
        avatar: '/ecomondo/speakers/LUISA_GONZALEZ.webp',
        resume_es: 'Ingeniera ambiental y química de la Universidad de los Andes en Bogotá, con doctorado en Ingeniería de Procesos de la Ecole des Mines de Nantes, Francia, con énfasis en tecnologías de remoción de contaminantes atmosféricos. Actualmente, apoya a la Coalición Clima y Aire Limpio, gestionando proyectos para mitigar los contaminantes climáticos de vida corta, como una iniciativa del Programa de las Naciones Unidas para el Medio Ambiente (PNUMA). También, colabora con la agenda de calidad del aire en el Programa de Productos Químicos y Contaminación de la Oficina del PNUMA para América Latina y el Caribe. Cuenta con más de 12 años de experiencia profesional en diferentes actividades académicas y de investigación, consultoría ambiental y servicio en el sector público ambiental, relacionadas con la medición de contaminantes en fuentes, monitoreo de la calidad del aire, desarrollo de políticas, gestión de proyectos entre otras actividades relacionadas con la gestión integrada de la calidad del aire y mitigación de contaminantes climáticos.',
        resume_en: 'Environmental and chemical engineer from Universidad de los Andes in Bogotá, with a PhD in Process Engineering from Ecole des Mines de Nantes, France, with emphasis on air pollutant removal technologies. Currently, he supports the Climate and Clean Air Coalition, managing projects to mitigate short-lived climate pollutants, as an initiative of the United Nations Environment Program (UNEP). He also collaborates with the air quality agenda in the Chemicals and Pollution Program of the UNEP Office for Latin America and the Caribbean. He has more than 12 years of professional experience in different academic and research activities, environmental consulting and service in the public environmental sector, related to the measurement of pollutants in sources, air quality monitoring, policy development, project management among other activities related to integrated air quality management and mitigation of climate pollutants.',
    },
    {
        id:16,
        name: 'Alejandra Bolio Rojas',
        avatar: '/ecomondo/speakers/alejandra_rojas.webp',
        resume_es: 'Consultora ambiental con más de 15 años de experiencia, ha dado un giro significativo en su carrera al adentrarse en el servicio público. Integrando sus habilidades de vinculación y sus conocimientos en Derecho Ambiental, Administración y Finanzas, ha encontrado una nueva forma de contribuir al bienestar de la comunidad.Su transición hacia el servicio público ha sido fluida y fructífera, demostrando su capacidad para adaptarse y aplicar sus habilidades de manera efectiva en este nuevo contexto. Alejandra, reconoce la importancia del trabajo en equipo y el valor de las alianzas estratégicas para lograr resultados significativos en el ámbito ambiental.',
        resume_en: 'She is an environmental consultant with more than 15 years of experience, has taken a significant turn in her career by entering public service. By integrating her outreach skills and her knowledge in environmental law, administration and finance, she has found a new way to contribute to the welfare of the community. Her transition into public service has been smooth and fruitful, demonstrating her ability to adapt and apply her skills effectively in this new context. Alejandra recognizes the importance of teamwork and the value of strategic alliances to achieve significant results in the environmental field.',
    },
    {
        id:19,
        name: 'Luca Torresan',
        avatar: '/ecomondo/speakers/luca_torresan.webp',
        resume_es: 'Ingeniero medioambiental, entusiasta de la economía circular y miembro activo de ISWA, trabaja en el campo de la gestión de residuos desde 2007. Ha experimentado el desarrollo y la difusión de prácticas de reducción y separación de residuos, tanto en Italia como a nivel internacional. Con más de 15 años de experiencia en la gestión de socios nacionales y mundiales, desarrollando proyectos e impulsando el crecimiento del modelo, su trayectoria hace especial hincapié en la exportación y remodelación del modelo italiano de recogida selectiva de biorresiduos. ',
        resume_en: 'Environmental Engineer, Circular Economy enthusiast and active ISWA member he has working in the field of waste management since 2007. Has experienced the development and spread of waste reduction and separation practices, both in Italy and internationally. With over 15 years of experience in managing national and worldwide partners, developing projects and driving the model growth, his background has particular emphasis on exporting and re-modelling the Italian model of separate collection of bio-waste.',
    },
    {
        id:20,
        name: 'Omar Palafox Saenz',
        avatar: '/ecomondo/speakers/omar-palafox_v3.webp',
        resume_es: 'Ingeniero Industrial por el ITESO. Cuenta con una maestría en manufactura avanzada, por el ESADE; una maestría en Innovación Educativa, por la Universidad Antropológica de Guadalajara; y, maestría de Ingeniería Medioambiental y Sustentabilidad, por la Universidad Tecnológica de Latinoamérica. Asimismo tiene diferentes especialidades en Finanzas, Marketingt y Dirección de empresas. También, se desempeñó como asesor en proyectos medioambientales y de Economía Circular, Project Manager de proyectos en Tepatitlán de Morelos, Cd. Juárez, Churintzio. Actualmente, es Coordinador Zona Occidente, de Grupo Serrano, empresa dedicada a lácteos, ganadería, agricultura, porcicultura, reciclaje y generación de energías verdes con desechos orgánicos; funge como representante de la empresa en la Alianza Empresarial por el Clima, y es representante ciudadano en Tlajomulco, en el Consejo de Gobierno Abierto y Transparencia.',
        resume_en: 'Industrial Engineer from ITESO. He has a master\'s degree in advanced manufacturing from ESADE; a master\'s degree in Educational Innovation from the Universidad Antropológica de Guadalajara; and a master\'s degree in Environmental Engineering and Sustainability from the Universidad Tecnológica de Latinoamérica. He also has different specialties in Finance, Marketing and Business Management. He has also worked as a consultant in environmental and Circular Economy projects, Project Manager of projects in Tepatitlán de Morelos, Cd. Juárez, Churintzio. Currently, he is the Western Zone Coordinator of Grupo Serrano, a company dedicated to dairy, livestock, agriculture, pig farming, recycling and generation of green energy with organic waste; he serves as a representative of the company in the Business Alliance for Climate, and is a citizen representative in Tlajomulco, in the Council of Open Government and Transparency.',
    },
    {
        id:21,
        name: 'Christian Mulcahy ',
        avatar: '/ecomondo/speakers/christian-mulcahy.webp',
        resume_es: 'Ingeniero Ambiental con 20 años de experiencia en diversas áreas ambientales y sociales, como estión de residuos, remediación de sitios contaminados, Economía Circular, e informes de sostenibilidad y ESG (Environmental, Social, and Governance). Apasionado por encontrar soluciones a los desafíos actuales como sociedad ante el cambio climático, el uso sostenible de recursos y la gestión de residuos.En los últimos años, ha orientado su carrera hacia la gestión de negocios relacionados con la gestión de residuos orgánicos y la agricultura sostenible, dos pilares fundamentales en la lucha contra el cambio climático y en la búsqueda de un futuro más sostenible. Su enfoque actual es el desarrollo e implementación de soluciones sostenibles para la gestión de residuos orgánicos en Iberia y América Latina con Compost Systems GmbH.',
        resume_en: 'Environmental Engineer with 20 years of experience in various environmental and social areas, such as waste management, remediation of contaminated sites, Circular Economy, and sustainability and ESG (Environmental, Social, and Governance) reporting. Passionate about finding solutions to current challenges as a society in the face of climate change, sustainable resource use and waste management. In recent years, he has oriented his career towards the management of businesses related to organic waste management and sustainable agriculture, two fundamental pillars in the fight against climate change and in the search for a more sustainable future. His current focus is the development and implementation of sustainable solutions for organic waste management in Iberia and Latin America with Compost Systems GmbH.',
    },
    {
        id:22,
        name: 'Alberto Carmona Velázquez',
        avatar: '/ecomondo/speakers/alberto_carmona.webp',
        resume_es: 'Biólogo graduado de la Universidad Autónoma de Aguascalientes, con una amplia trayectoria académica, la cual incluye una maestría en Política y Gestión Energética Medioambiental, de la Facultad Latinoamericana de Ciencias Sociales (FLACSO); estudios de posgrado en Energías Renovables, en la Universidad de Ciencias Aplicadas de Wismar, Alemania; y, estudios en Alta Dirección y Gerencia Pública para el Desarrollo Local, en el Centro de Investigación y Docencia Económicas (CIDE); así como en Finanzas Sostenibles y Análisis de Riesgos, en el Instituto Tecnológico Autónomo de México (ITAM). Ha representado a México como observador e integrante de la Delegación Mexicana en varias Conferencias de las Partes de la Convención Marco de las Naciones Unidas sobre el Cambio Climático. En su carrera profesional, ha ocupado diversos cargos relacionados con la protección ambiental y la política ambiental en instituciones públicas, incluyendo roles como Coordinador General de la Oficina de Protección Ambiental, de la Universidad Autónoma de Aguascalientes; Asistente de Investigación, en el Instituto Fraunhofer en Alemania; y múltiples posiciones en el gobierno del los estados de Aguascalientes y Guanajuato, donde actualmente se desempeña como Encargado de Despacho, en la Secretaría de Medio Ambiente y Ordenamiento Territorial del Estado de Guanajuato.',
        resume_en: 'Biologist graduated from the Universidad Autónoma de Aguascalientes, with an extensive academic career, which includes a \'s degree in Environmental Energy Policy and Management, from the Latin American Faculty of Social Sciences (FLACSO); postgraduate studies in Renewable Energies, at the University of Applied Sciences of Wismar, Germany; and studies in Senior Management and Public Management for Local Development at the Centro de Investigación y Docencia Económicas (CIDE), as well as in Sustainable Finance and Risk Analysis at the Instituto Tecnológico Autónomo de México (ITAM). He has represented Mexico as an observer and member of the Mexican Delegation in several Conferences of the Parties to the United Nations Framework Convention on Climate Change. In his professional career, he has held various positions related to environmental protection and environmental policy in public institutions, including roles as General Coordinator of the Environmental Protection Office of the Autonomous University of Aguascalientes; Research Assistant at the Fraunhofer Institute in Germany; and multiple positions in the government of the states of Aguascalientes and Guanajuato, where he is currently in charge of the Office of the Secretary of Environment and Territorial Planning of the State of Guanajuato.',
    },
    {
        id:17,
        name: 'Efraín Aguirrre Macías',
        avatar: '/ecomondo/speakers/user_img.webp',
        resume_es: 'Ingeniero agrónomo egresado del Centro Universitario de Ciencias Biológicas y Agropecuarias en 1979, ha dejado una marca significativa en diversos campos a lo largo de su carrera profesional. Durante su tiempo en la Secretaría de Agricultura y Recursos Hidráulicos como jefe de unidad en la Región de Cd. Guzmán, Jalisco, entre 1985 y 1995, se destacó por su aguda capacidad de resolución de problemas y compromiso con encontrar soluciones efectivas para los desafíos agrícolas. Posteriormente, como contratista en la Comisión Federal de Electricidad, coordinó servicios de calidad en la poda de líneas de alta tensión y el mantenimiento de subestaciones en todo el país. Además, viajó a países como Holanda, Estados Unidos, Japón y Colombia para explorar procesos avanzados de compostaje. Como resultado, estableció la planta de compostaje industrial El Morado Compost, líder en el sector, que ha contribuido al avance y la sostenibilidad de la industria mediante la implementación de métodos novedosos y la publicación de investigaciones científicas para eficientar procesos.',
        resume_en: 'He is an agronomist graduated from the Centro Universitario de Ciencias Biológicas y Agropecuarias in 1979, and has left a significant mark in various fields throughout his professional career. During his time at the Ministry of Agriculture and Hydraulic Resources as head of unit in the region of Cd. Guzman, Jalisco, between 1985 and 1995, he stood out for his sharp problem-solving skills and commitment to finding effective solutions to agricultural challenges. Later, as a contractor for the Federal Electricity Commission, he coordinated quality services in high-voltage line trimming and substation maintenance throughout the country. In addition, he traveled to countries such as Holland, the United States, Japan and Colombia to explore advanced composting processes. As a result, he established the industrial composting plant El Morado Compost, a leader in the sector, which has contributed to the advancement and sustainability of the industry through the implementation of novel methods and the publication of scientific research to make processes more efficient.',
    },
    {
        id:18,
        name: 'Rodrigo Gómez Rizo',
        avatar: '/ecomondo/speakers/user_img.webp',
        resume_es: 'Licenciado en Biología comprometido con la preservación del medio ambiente y el desarrollo sostenible. Con una década de experiencia en la industria del compostaje, ha demostrado habilidades para innovar y liderar en este campo. Actualmente, es gerente de calidad y desarrollo tecnológico en El Morado Compost, donde promueve prácticas ambientales responsables. Paralelamente, está cursando una Maestría en Ciencias de Productos Forestales en la UDG, buscando enfrentar los desafíos ambientales con soluciones basadas en la ciencia y la innovación. Su combinación de experiencia y formación lo posiciona como un líder en la gestión ambiental y la industria del compostaje.',
        resume_en: 'Biology graduate committed to environmental preservation and sustainable development. With a decade of experience in the composting industry, he has demonstrated skills to innovate and lead in this field. He is currently manager of quality and technological development at El Morado Compost, where he promotes responsible environmental practices. In parallel, he is pursuing a Master of Science in Forest Products at UDG, seeking to address environmental challenges with solutions based on science and innovation. His combination of experience and training positions him as a leader in environmental management and the composting industry.',
    },
    {
        id:23,
        name: 'Eduardo Walsh',
        avatar: '/ecomondo/speakers/eduardo-walsh.webp',
        resume_es: 'Licenciado en Economía por la Universidad Nacional Autónoma de México. Gerente de Proyectos de la Konrad-Adenauer-Stiftung México, enfocado en dirigir y desarrollar proyectos sobre economía, democracia, partidos políticos, empoderamiento de comunidades indígenas, energía, medio ambiente, desarrollo sustentable, entre otros. Ha colaborado como asesor en la Honorable Cámara de Diputados, así como en la Asamblea Legislativa del Distrito Federal. Cuenta también con experiencia en el sector privado, colaborando con empresas de energía y desarrollo sustentable. Autor de las obras “México, hacia una transición energética”, “Alianza Centro-Bajío-Occidente, un modelo de progreso, económico, social y medioambiental”,y “El ABC de la gestión energética y el combate al cambio climático a nivel subnacional”, entre otras. Es miembro del Consejo Consultivo del Índice de Gestión Energética y Cambio Climático (IGECC), proyecto de cooperación internacional enfocado en la evaluación de las políticas públicas de gobiernos subnacionales, en materia de combate al cambio climático y el desarrollo sustentable.',
        resume_en: 'Graduated in Economics from the Universidad Nacional Autónoma de México. Project Manager at Konrad-Adenauer-Stiftung Mexico, focused on directing and developing projects on economics, democracy, political parties, empowerment of indigenous communities, energy, environment, sustainable development, among others. He has collaborated as an advisor in the Honorable Chamber of Deputies, as well as in the Legislative Assembly of the Federal District. He also has experience in the private sector, collaborating with energy and sustainable development companies. He is the author of "Mexico, towards an energy transition", "Alianza Centro-Bajío-Occidente, a model of progress, economic, social and environmental", and "El ABC de la gestión energética y el combate al cambio climático a nivel subnacional", among others. He is a member of the Advisory Board of the Energy Management and Climate Change Index (IGECC), an international cooperation project focused on the evaluation of public policies of subnational governments in the fight against climate change and sustainable development.',
    },
     {
        id:21,
        name: 'Martín Argueta',
        avatar: '/ecomondo/speakers/martin-argueta.webp',
        resume_es: 'La información se está actualizando. Por favor, mantente atento.',
        resume_en: 'Information is being updated. Please stay tuned.',
    },
     {
        id:21,
        name: 'Karina Márquez Guzmán',
        avatar: '/ecomondo/speakers/karina-marquez.webp',
        resume_es: 'La información se está actualizando. Por favor, mantente atento.',
        resume_en: 'Information is being updated. Please stay tuned.',
    },
     {
        id:21,
        name: 'Marcelo Rosso',
        avatar: '/ecomondo/speakers/marcelo-rosso.webp',
        resume_es: 'La información se está actualizando. Por favor, mantente atento.',
        resume_en: 'Information is being updated. Please stay tuned.',
    },
     {
        id:21,
        name: 'Bruno García Dancourt',
        avatar: '/ecomondo/speakers/bruno-garcia.webp',
        resume_es: 'La información se está actualizando. Por favor, mantente atento.',
        resume_en: 'Information is being updated. Please stay tuned.',
    },
     // {
    //     id:21,
    //     name: '',
    //     avatar: '/ecomondo/speakers/user_img.webp',
    //     resume_es: '',
    //     resume_en: '',
    // },
]
export { speakers }
  